# Generated by Django 3.2.7 on 2021-09-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.IntegerField()),
                ('store_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100)),
            ],
        ),
    ]
