# Generated by Django 3.2.7 on 2021-09-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=50)),
                ('store_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(choices=[(1, 'Eletrodomésticos'), (2, 'Eletronicos'), (3, 'Móveis')], max_length=50)),
                ('product', models.CharField(choices=[(1, 'Geladeira'), (2, 'Celular'), (3, 'Sofá')], max_length=100)),
            ],
        ),
    ]
